// import { isConditionalExpression } from "typescript";

export const userScores = [
    {
        id: 1,
        Name: "peter White",
        age: 16,
        gender: "male",
        score: 85,
        class: "ss1",
        isActive: true,
        school: "jewel for christ ",
    },
    {
        id: 2,
        Name: "Miracle Chioma",
        age: 21,
        gender: "female",
        score: 69,
        class: "ss3",
        isActive: false,
    },
    {
        id: 3,
        Name: "paul walker",
        age: 18,
        score: 90,
        gender: "male",
        class: "ss1",
        school: "Sit of wisdom ",
        isActive: true
    },
    {
        id: 4,
        Name: "peter pan",
        age: 22,
        score: 89,
        gender: "male",
        class: "ss3",
        school: "Madona ",
        isActive: true
    },
    {
        id: 5,
        Name: "July Ann",
        age: 16,
        score: 45,
        gender: "female",
        class: "ss1",
        school: "jewel for christ ",
        isActive: true
    },
    {
        id: 6,
        Name: "John Doe",
        age: 15,
        score: 95,
        gender: "male",
        class: "jss3",
        school: "jewel for christ ",
        isActive: true
    },
    {
        id: 7,
        Name: " Nikxin Lechi",
        age: 25,
        gender: "male",
        score: 89,
        isActive: false,
    },
    {
        id: 8,
        Name: "Banny Vik",
        age: 21,
        gender: "male",
        score: 91,
        isActive: false,
    },
    {
        id: 9,
        Name: "Angel paul",
        age: 19,
        score: 49,
        gender: "female",
        class: "ss2",
        school: "Development high school ",
        isActive: true
    },
    {
        id: 10,
        Name: "nancy james",
        age: 13,
        score: 88,
        gender: "female",
        class: "jss2",
        school: "jewel for christ ",
        isActive: true
    },
    {
        id: 11,
        Name: " barbie bae",
        age: 25,
        gender: "female",
        score: 45,
        isActive: false,
    },
    {
        id: 12,
        Name: "Chioma Joy",
        age: 8,
        gender: "female",
        score: 73,
        class: "jss1",
        school: "jewel for christ ",
        isActive: true
    },
    {
        id: 13,
        Name: "Jude A",
        age: 9,
        gender: "male",
        score: 61,
        class: "jss2",
        school: "jewel for christ ",
        isActive: true
    },
    {
        id: 14,
        Name: "charls clft",
        age: 24,
        gender: "male",
        score: 57,
        isActive: false,
    },
    {
        id: 15,
        Name: "chukwudi E",
        age: 26,
        gender: "male",
        score: 61,
        isActive: false,
    },
    {
        id: 16,
        Name: "peter A",
        age: 40,
        gender: "male",
        score: 87,
        isActive: false,
    },
    {
        id: 17,
        Name: "Baby Nai",
        age: 7,
        gender: "female",
        score: 50,
        class: "jss1",
        school: "jewels ",
        isActive: true
    },
    {
        id: 18,
        Name: "Ijeoma I",
        age: 20,
        gender: "female",
        score: 100,
        level: 100,
        school: "high school",
        isActive: true
    },
    {
        id: 19,
        Name: "confidence P",
        age: 21,
        gender: "female",
        score: 70,
        level: 300,
        school: "Uni-port",
        isActive: true
    },
    {
        id: 20,
        Name: "mary ann",
        age: 29,
        gender: "female",
        score: 51,
        level: 200,
        school: "In school",
        isActive: true
    },
    {
        id: 21,
        Name: "chibuzor A",
        age: 24,
        gender: "male",
        score: 67,
        isActive: true
    },
    {
        id: 22,
        Name: "peter White",
        age: 16,
        gender: "male",
        score: 85,
        class: "ss1",
        isActive: true,
        school: "jewel for christ ",
    },
    {
        id: 23,
        Name: "Miracle Chioma",
        age: 21,
        gender: "female",
        score: 69,
        class: "ss3",
        isActive: false,
    },
    {
        id: 24,
        Name: "paul walker",
        age: 18,
        score: 90,
        gender: "male",
        class: "ss1",
        school: "Sit of wisdom ",
        isActive: true
    },
    {
        id: 25,
        Name: "peter pan",
        age: 22,
        score: 89,
        gender: "male",
        class: "ss3",
        school: "Madona ",
        isActive: true
    },
    {
        id: 26,
        Name: "July Ann",
        age: 16,
        score: 45,
        gender: "female",
        class: "ss1",
        school: "jewel for christ ",
        isActive: true
    },
    {
        id: 27,
        Name: "John Doe",
        age: 15,
        score: 95,
        gender: "male",
        class: "jss3",
        school: "jewel for christ ",
        isActive: true
    },
    {
        id: 28,
        Name: " Nikxin Lechi",
        age: 25,
        gender: "male",
        score: 89,
        isActive: false,
    },
    {
        id: 29,
        Name: "Banny Vik",
        age: 21,
        gender: "male",
        score: 91,
        isActive: false,
    },
    {
        id: 30,
        Name: "Angel paul",
        age: 19,
        score: 49,
        gender: "female",
        class: "ss2",
        school: "Development high school ",
        isActive: true
    },
    {
        id: 31,
        Name: "nancy james",
        age: 13,
        score: 88,
        gender: "female",
        class: "jss2",
        school: "jewel for christ ",
        isActive: true
    },
    {
        id: 32,
        Name: " barbie bae",
        age: 25,
        gender: "female",
        score: 45,
        isActive: false,
    },
    {
        id: 33,
        Name: "Chioma Joy",
        age: 8,
        gender: "female",
        score: 73,
        class: "jss1",
        school: "jewel for christ ",
        isActive: true
    },
    {
        id: 34,
        Name: "Jude A",
        age: 9,
        gender: "male",
        score: 61,
        class: "jss2",
        school: "jewel for christ ",
        isActive: true
    },
    {
        id: 35,
        Name: "charls clft",
        age: 24,
        gender: "male",
        score: 57,
        isActive: false,
    },
    {
        id: 36,
        Name: "chukwudi E",
        age: 26,
        gender: "male",
        score: 61,
        isActive: false,
    },
    {
        id: 37,
        Name: "peter A",
        age: 40,
        gender: "male",
        score: 87,
        isActive: false,
    },
    {
        id: 38,
        Name: "Baby Nai",
        age: 7,
        gender: "female",
        score: 50,
        class: "jss1",
        school: "jewels ",
        isActive: true
    },
    {
        id: 39,
        Name: "Ijeoma I",
        age: 20,
        gender: "female",
        score: 100,
        level: 100,
        school: "high school",
        isActive: true
    },
    {
        id: 40,
        Name: "confidence P",
        age: 21,
        gender: "female",
        score: 70,
        level: 300,
        school: "Uni-port",
        isActive: true
    },
    {
        id: 41,
        Name: "mary ann",
        age: 29,
        gender: "female",
        score: 51,
        level: 200,
        school: "In school",
        isActive: true
    },
    {
        id: 42,
        Name: "chibuzor DE",
        age: 30,
        gender: "male",
        score: 76,
        level: 300,
        school: "In school",
        isActive: true
    },
    {
        id: 43,
        Name: "paul White",
        age: 14,
        gender: "male",
        score: 81,
        class: "ss1",
        isActive: true,
        school: "jewel for christ ",
    },
    {
        id: 44,
        Name: "Miracle Chioma",
        age: 45,
        gender: "female",
        score: 69,
        isActive: false,
    },
    {
        id: 45,
        Name: "paul walkins",
        age: 18,
        score: 30,
        gender: "male",
        class: "ss1",
        school: "Sit of wisdom ",
        isActive: true
    },
    {
        id: 46,
        Name: "pee pan",
        age: 22,
        score: 77,
        gender: "male",
        class: "ss3",
        school: "Madona ",
        isActive: true
    },
    {
        id: 47,
        Name: "Joy Ann",
        age: 13,
        score: 59,
        gender: "female",
        class: "ss1",
        school: "jewel for christ ",
        isActive: true
    },
    {
        id: 48,
        Name: "John Gool",
        age: 18,
        score: 46,
        gender: "male",
        class: "jss3",
        school: "hero of faith ",
        isActive: true
    },
    {
        id: 49,
        Name: " Noti ing",
        age: 34,
        gender: "male",
        score: 80,
        isActive: false,
    },
    {
        id: 50,
        Name: "Danny Vik",
        age: 31,
        gender: "male",
        score: 60,
        isActive: false,
    },
    {
        id: 51,
        Name: "Angela paul",
        age: 18,
        score: 48,
        gender: "female",
        class: "ss2",
        school: "Development high school ",
        isActive: true
    },
    {
        id: 52,
        Name: "nancy j",
        age: 14,
        score: 70,
        gender: "female",
        class: "jss2",
        school: "madona ",
        isActive: true
    },
    {
        id: 53,
        Name: " Di bae",
        age: 23,
        gender: "female",
        score: 50,
        isActive: false,
    },
    {
        id: 54,
        Name: "Chioma Joy",
        age: 8,
        gender: "female",
        score: 90,
        class: "jss1",
        school: "jewels",
        isActive: true
    },
    {
        id: 55,
        Name: "John A",
        age: 9,
        gender: "male",
        score: 65,
        class: "jss2",
        school: "jewels ",
        isActive: true
    },
    {
        id: 56,
        Name: "clft clft",
        age: 18,
        gender: "male",
        score: 40,
        isActive: false,
    },
    {
        id: 57,
        Name: "chuk R",
        age: 20,
        gender: "male",
        score: 55,
        isActive: false,
    },
    {
        id: 58,
        Name: "pet A",
        age: 41,
        gender: "male",
        score: 62,
        isActive: false,
    },
    {
        id: 59,
        Name: "Baby Nai",
        age: 6,
        gender: "female",
        score: 50,
        class: "jss1",
        school: "jewels ",
        isActive: true
    },
    {
        id: 60,
        Name: "Ijeoma e",
        age: 21,
        gender: "female",
        score: 100,
        level: 400,
        school: "high school",
        isActive: true
    },


]